name: 0.0.$(BuildId)

variables:
- name: Version
  value: $(Build.BuildNumber)
- group: FeedSettings

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    vstsFeed: '$(AccountFeed)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    arguments: '--no-restore -p:Version=$(Version)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    arguments: '--no-build --collect "Code coverage"'
    
- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    nobuild: true

- task: DotNetCoreCLI@2
  displayName: Push to Azure
  inputs:
    command: push
    publishVstsFeed: '$(AccountFeed)'

- task: DotNetCoreCLI@2
  displayName: Push to NuGet.org
  inputs:
    command: 'push'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'XtateFeed'
