name: Publish Dependencies

on:
  registry_package:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.BOT_ACTION_TOKEN }}

jobs:
  trigger:
    name: Publish ${{ matrix.repo }}
    strategy:
      matrix:
        repo: []
    
    runs-on: ubuntu-latest
  
    steps:
      - name: Workflow Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Publish
          token: ${{ secrets.BOT_ACTION_TOKEN }}
          repo: ${{ matrix.repo }}
          ref: master
